### ISSUE TITLE
Error: find method in UnionFind with path compression and union by rank

### ISSUE THREAD

**Issue by srikarplus** [LeetCode-Feedback/LeetCode-Feedback#5193]
#### Your LeetCode username
srikarplus

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Content

#### Description of the bug

https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3843/
When path compression is used along with union by rank, upon calling find method the rank also should get updated.

#### Code you used for Submit/Run operation

``` python
# UnionFind class
class UnionFind:
    def __init__(self, size):
        self.root = [i for i in range(size)]
        # Use a rank array to record the height of each vertex, i.e., the "rank" of each vertex.
        # The initial "rank" of each vertex is 1, because each of them is
        # a standalone vertex with no connection to other vertices.
        self.rank = [1] * size

    # The find function here is the same as that in the disjoint set with path compression.
    def find(self, x):
        if x == self.root[x]:
            return x
        self.root[x] = self.find(self.root[x])
        return self.root[x]

    # The union function with union by rank
    def union(self, x, y):
        rootX = self.find(x)
        rootY = self.find(y)
        if rootX != rootY:
            if self.rank[rootX] > self.rank[rootY]:
                self.root[rootY] = rootX
            elif self.rank[rootX] < self.rank[rootY]:
                self.root[rootX] = rootY
            else:
                self.root[rootY] = rootX
                self.rank[rootX] += 1

    def connected(self, x, y):
        return self.find(x) == self.find(y)

```

#### Language used for code

Python 3

#### Current behavior

``` python
# Test Case
uf = UnionFind(4)
uf.union(0, 3)
uf.union(1, 2)
uf.union(2, 3)



print(uf.root) // [1, 1, 1, 0]
print(uf.rank) // [2, 3, 1, 1]

uf.find(3)

print(uf.root) // [1, 1, 1, 1]
print(uf.rank) // [2, 3, 1, 1] <----
```

#### Expected behavior
``` python
# Test Case
uf = UnionFind(4)
uf.union(0, 3)
uf.union(1, 2)
uf.union(2, 3)



print(uf.root) // [1, 1, 1, 0]
print(uf.rank) // [2, 3, 1, 1]

uf.find(3)

print(uf.root) // [1, 1, 1, 1]
print(uf.rank) // [1, 2, 1, 1]  <----
```

**Comment by srikarplus** [comment]
@LC-Sue can u please take a look

**Comment by LC-Sue** [comment]
Hi @srikarplus 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @srikarplus 
Thank you for your concern. You are correct in noticing that rank[node] will not always be correct when using this method.

However, there is no need to update it for the disjoint set data structure to function properly. Notice that the only time we refer to rank is when we are deciding which root node has a higher rank. So it only matters that the root node has the correct rank.

This is addressed by the line: rank[rootX] += 1;. When we point one root to another root and both roots have the same rank, then the new root's rank increases by one.

On the other hand if we point a lower rank root to a higher rank root, the rank will remain the same and no update is needed.

In this way the root node will always have the correct rank and the data structure we will still see the benefits of path compression and union by rank without needing to update the rank of every node.

**Comment by nikhiljain217** [comment]
This is still an issue with the optimization. 
Lets consider this case:
Lets take 10 nodes (0-9);
This is the first few union call
union(0,1);
union(1,2);
union(2,3);
union(3,4);
union(4,5);
union(5,6);

This will create skew tree, 0->1->2->3->4->5->6 with rank[0]=7, Further calls:
union(7,8);
union(8,9);
This is create separate tree 7->8->9, with rank[7]=3. Now, find is called on node 6,
find(6)
Now, the first tree will change where 0 is connected directly with all the tree because of path compression. If the client code call union(0,7). It will end up making 7 as child of 0 because the rank[0] is still 7 which will result in a tree of height 4. But, if we have updated the rank with path compression, the tree would be 3. So, by not updating the rank, this code is missing the optimization which was done by union by rank.

**Comment by LPRowe** [comment]
Hi @nikhiljain217 thank you for sharing your thoughts.

Although, I think there might be a small oversight in your example:

>This is the first few union call
>union(0,1);
>union(1,2);
>union(2,3);
>union(3,4);
>union(4,5);
>union(5,6);
>
>This will create skew tree, 0->1->2->3->4->5->6 with rank[0]=7

We are pointing `rootX` to `rootY` or `rootY` to `rootX` depending on each root's rank.
We are not pointing `x` to `y` or `y` to `x`, so this skewed tree structure will never occur.

Using your example for clarity:

union(0, 1) results in 0<-1 because 0 and 1 both have rank 1, we reach the else statement. rank[0] gets updated from 1 to 2.

union(1, 2) finds the root of 1 (which is 0) and the root of 2 (which is 2).  The rank of node 0 is 2 and the rank of node 2 is 1 so this time we point the root of node 2 (which is 2) to the root of node 1 (which is zero) so now we have:

```
0
|\
1 2
```

And because we pointed a lower rank root to a higher rank root, the rank of root zero does not change (it remains 2).
  
union(2, 3) will find the root of 2 (which is 0) and the root of 3 (which is 3).
The rank of node 0 is 2 and the rank of node 3 is 1, so we will point node 3 to node 0.

```
  0
 /|\
1 2 3
```

So the "skew tree, 0->1->2->3->4->5->6" will not arise from this type of input.

**Comment by nikhiljain217** [comment]
That make sense. Thank you the response.
